image:
  file: .gitpod.Dockerfile

ports:
  - port: 3333

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - PKief.material-icon-theme@4.3.0:URe4ANXBLYHzB6CeGyTN8A==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==